### ISSUE TITLE
如何渲染html格式文章里的公式

### ISSUE THREAD

**Issue by Compassen** [Shimada666/VaTex#4]
请问下作者大大，假如我是html格式的文章，里面有公式，如下格式<span data-w-e-type="formula" data-w-e-is-void data-w-e-is-inline data-value="c = \\pm\\sqrt{a^2 + b^2}"></span>，该如何渲染呢

**Comment by Shimada666** [comment]
那应该要把文章中的公式提出来传入组件渲染
